<a href="https://colab.research.google.com/github/michaelosen/michaelosen/blob/main/activity_pillar_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
response = requests.get('https://httpbin.org/ip')
print(f"My public IP address is: {response.json()['origin']}")

My public IP address is: 34.80.159.50

In [ ]:
#Github

! apt-get install git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.

In [ ]:
!git clone https://github.com/michaelosen/wone-notebooks.git

Cloning into 'wone-notebooks'...
fatal: could not read Username for 'https://github.com': No such device or address

Authenticatng google user

In [ ]:
# Authenticate with GCP

from google.colab import auth
auth.authenticate_user()
print("Authenticated")

Authenticated

Setting up google environment

In [ ]:
!pip install sqlalchemy-bigquery

Requirement already satisfied: sqlalchemy-bigquery in /usr/local/lib/python3.10/dist-packages (1.12.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy-bigquery) (2.19.2)
Requirement already satisfied: google-auth<3.0.0dev,>=1.25.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy-bigquery) (2.27.0)
Requirement already satisfied: google-cloud-bigquery<4.0.0dev,>=3.3.6 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy-bigquery) (3.25.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from sqlalchemy-bigquery) (24.1)
Requirement already satisfied: sqlalchemy<3.0.0dev,>=1.4.16 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy-bigquery) (2.0.36)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery) (1.65.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery) (3.20.3)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery) (1.24.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery) (2.32.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0.0dev,>=1.25.0->sqlalchemy-bigquery) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0.0dev,>=1.25.0->sqlalchemy-bigquery) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0.0dev,>=1.25.0->sqlalchemy-bigquery) (4.9)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery<4.0.0dev,>=3.3.6->sqlalchemy-bigquery) (2.4.1)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery<4.0.0dev,>=3.3.6->sqlalchemy-bigquery) (2.7.2)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery<4.0.0dev,>=3.3.6->sqlalchemy-bigquery) (2.8.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<3.0.0dev,>=1.4.16->sqlalchemy-bigquery) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<3.0.0dev,>=1.4.16->sqlalchemy-bigquery) (3.1.1)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery<4.0.0dev,>=3.3.6->sqlalchemy-bigquery) (1.64.1)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery<4.0.0dev,>=3.3.6->sqlalchemy-bigquery) (1.48.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<4.0.0dev,>=3.3.6->sqlalchemy-bigquery) (1.6.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.25.0->sqlalchemy-bigquery) (0.6.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3.0dev,>=2.7.2->google-cloud-bigquery<4.0.0dev,>=3.3.6->sqlalchemy-bigquery) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->sqlalchemy-bigquery) (2024.8.30)

In [ ]:
# load libraries and packages

from google.cloud import bigquery
from sqlalchemy import create_engine
from IPython.display import display, HTML
import pandas as pd

In [ ]:
# set project id for BigQuery

project_id = 'woe-system'

In [ ]:
# set client for BigQuery

client = bigquery.Client(project=project_id)

In [ ]:
# Construct a BigQuery connection string
# Replace with your project ID, dataset ID, etc.
BQ_rdsds_connection_string = f'bigquery://woe-system/postgres_rds_public_datstream'

In [ ]:
# Create an engine using SQLAlchemy
engine = create_engine(BQ_rdsds_connection_string)

In [ ]:
# Your SQL query
sql_query = """
SELECT *
FROM woe-system.postgres_rds_public_datstream.public_biometrics_vital_summary_activity
LIMIT 10;
"""

In [ ]:
# Execute the query using pandas and SQLAlchemy
df = pd.read_sql_query(sql_query, engine)

In [ ]:
# Print or work with the DataFrame
display(df)

,created_at,updated_at,id,date,vital_id,calories_total,calories_active,steps,daily_movement,low,...,floors_climbed,time_zone,timezone_offset,data_json,raw_data_json,created_by_message_id,source_id,updated_by_message_id,user_id,datastream_metadata
0,2023-05-07 10:07:52.336653+00:00,2023-05-07 10:07:52.336675+00:00,184,2023-05-04 00:00:00+00:00,bcf04e5a-bedb-4f55-9316-fce444a267f3,1730.0,0.0,NaN,0.0,NaN,...,NaN,None,19800,"{'calendar_date': '2023-05-04', 'calories_acti...",None,14089,17,NaN,17,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
1,2023-05-08 02:15:30.865580+00:00,2023-05-09 11:45:21.797893+00:00,188,2023-05-08 00:00:00+00:00,38fcea38-0faa-4c0a-bac5-fbb5b69e9899,1188.0,0.0,NaN,0.0,NaN,...,NaN,None,19800,"{'calendar_date': '2023-05-08', 'calories_acti...",None,14166,17,14703.0,17,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
2,2023-05-07 10:07:52.318287+00:00,2023-05-08 02:15:30.828178+00:00,182,2023-05-07 00:00:00+00:00,b55abe34-589a-4e7b-9570-20ef0e8314c3,1966.0,0.0,NaN,0.0,NaN,...,NaN,None,19800,"{'calendar_date': '2023-05-07', 'calories_acti...",None,14089,17,14165.0,17,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
3,2023-05-09 11:45:21.733035+00:00,2023-05-09 22:00:39.631589+00:00,368,2023-05-09 00:00:00+00:00,990940a0-b6b4-431a-b3b9-9c8c360618b9,955.0,0.0,NaN,0.0,NaN,...,NaN,None,19800,"{'calendar_date': '2023-05-09', 'calories_acti...",None,14702,17,15236.0,17,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
4,2023-05-07 10:07:52.328105+00:00,2023-05-07 10:07:52.328130+00:00,183,2023-05-06 00:00:00+00:00,04c2d9fb-fb60-4d56-a049-29a4a7502fb1,1314.0,0.0,NaN,0.0,NaN,...,NaN,None,19800,"{'calendar_date': '2023-05-06', 'calories_acti...",None,14089,17,NaN,17,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
5,2023-05-09 09:50:32.222520+00:00,2023-05-09 09:50:32.222553+00:00,362,2023-03-10 00:00:00+00:00,5cecbf73-95a9-4871-a37d-176a77a6b8f6,2508.0,90.0,3199.0,2719.0,319.0,...,5.0,None,0,"{'calendar_date': '2023-03-10', 'calories_acti...",None,14600,19,NaN,19,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
6,2023-05-09 09:50:18.672120+00:00,2023-05-09 09:50:18.672152+00:00,346,2023-03-27 00:00:00+00:00,9b98c0fd-ed43-4b73-ae00-5be08fbbaa55,3878.0,1460.0,22537.0,19161.0,249.0,...,12.0,None,7200,"{'calendar_date': '2023-03-27', 'calories_acti...",None,14544,19,NaN,19,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
7,2023-05-09 09:50:19.232060+00:00,2023-05-09 09:50:19.232092+00:00,350,2023-04-12 00:00:00+00:00,7217c788-8cf3-4867-b3fb-2bb2bb0161c8,3565.0,1147.0,11540.0,9808.0,242.0,...,5.0,None,7200,"{'calendar_date': '2023-04-12', 'calories_acti...",None,14549,19,NaN,19,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
8,2023-05-09 09:49:19.544254+00:00,2023-05-09 09:49:19.544284+00:00,283,2023-02-13 00:00:00+00:00,4de87622-dca6-4788-b441-1da7c83997d5,3322.0,702.0,8392.0,7322.0,274.0,...,13.0,None,0,"{'calendar_date': '2023-02-13', 'calories_acti...",None,14328,19,NaN,19,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
9,2023-05-09 09:49:59.156495+00:00,2023-05-09 09:49:59.156525+00:00,320,2023-04-02 00:00:00+00:00,450357f9-a9e3-4025-b9fe-84cbd4abcb48,2653.0,235.0,6920.0,5881.0,142.0,...,18.0,None,3600,"{'calendar_date': '2023-04-02', 'calories_acti...",None,14468,19,NaN,19,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...

In [ ]:
activity_data = client.query('''
SELECT * FROM `woe-system.postgres_rds_public_datstream.public_biometrics_vital_summary_activity` LIMIT 1000
''')

In [ ]:
df = activity_data.to_dataframe()

In [ ]:
df

,created_at,updated_at,id,date,vital_id,calories_total,calories_active,steps,daily_movement,low,...,floors_climbed,time_zone,timezone_offset,data_json,raw_data_json,created_by_message_id,source_id,updated_by_message_id,user_id,datastream_metadata
0,2024-10-14 23:00:02.348987+00:00,2024-10-14 23:00:02.349013+00:00,56065,2024-10-14 00:00:00+00:00,7d2d8987-8bea-b931-6ad6-a87eabf9c4dc,1370.0,1217.0,4018,8831.0,4189.0,...,4,None,0,"""{}""",None,<NA>,361,<NA>,314,{'uuid': '8c08ca31-9076-4d1b-bcaa-f1db00100010...
1,2023-05-07 10:07:52.328105+00:00,2023-05-07 10:07:52.328130+00:00,183,2023-05-06 00:00:00+00:00,04c2d9fb-fb60-4d56-a049-29a4a7502fb1,1314.0,0.0,<NA>,0.0,NaN,...,<NA>,None,19800,"{""calendar_date"":""2023-05-06"",""calories_active...",None,14089,17,<NA>,17,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
2,2023-05-07 10:07:52.318287+00:00,2023-05-08 02:15:30.828178+00:00,182,2023-05-07 00:00:00+00:00,b55abe34-589a-4e7b-9570-20ef0e8314c3,1966.0,0.0,<NA>,0.0,NaN,...,<NA>,None,19800,"{""calendar_date"":""2023-05-07"",""calories_active...",None,14089,17,14165,17,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
3,2023-05-07 10:07:52.336653+00:00,2023-05-07 10:07:52.336675+00:00,184,2023-05-04 00:00:00+00:00,bcf04e5a-bedb-4f55-9316-fce444a267f3,1730.0,0.0,<NA>,0.0,NaN,...,<NA>,None,19800,"{""calendar_date"":""2023-05-04"",""calories_active...",None,14089,17,<NA>,17,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
4,2023-05-08 02:15:30.865580+00:00,2023-05-09 11:45:21.797893+00:00,188,2023-05-08 00:00:00+00:00,38fcea38-0faa-4c0a-bac5-fbb5b69e9899,1188.0,0.0,<NA>,0.0,NaN,...,<NA>,None,19800,"{""calendar_date"":""2023-05-08"",""calories_active...",None,14166,17,14703,17,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
5,2023-05-09 11:45:21.733035+00:00,2023-05-09 22:00:39.631589+00:00,368,2023-05-09 00:00:00+00:00,990940a0-b6b4-431a-b3b9-9c8c360618b9,955.0,0.0,<NA>,0.0,NaN,...,<NA>,None,19800,"{""calendar_date"":""2023-05-09"",""calories_active...",None,14702,17,15236,17,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
6,2023-05-09 09:50:22.195733+00:00,2023-05-09 09:50:22.195761+00:00,356,2023-02-19 00:00:00+00:00,502fde03-34ba-4c24-aed1-8116b131b34d,5947.0,3529.0,23826,21240.0,100.0,...,18,None,0,"{""calendar_date"":""2023-02-19"",""calories_active...",None,14560,19,<NA>,19,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
7,2023-05-09 09:50:04.786433+00:00,2023-05-09 09:50:04.786463+00:00,330,2023-05-06 00:00:00+00:00,1d6a77b2-97b5-4dcd-ab60-d116ee453160,4364.0,1946.0,23715,20156.0,49.0,...,99,None,7200,"{""calendar_date"":""2023-05-06"",""calories_active...",None,14489,19,<NA>,19,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
8,2023-05-09 09:49:40.439914+00:00,2023-05-09 09:49:40.439945+00:00,300,2023-02-16 00:00:00+00:00,5811919d-82ac-4e43-b444-b972d3e08009,2861.0,241.0,1956,1721.0,195.0,...,0,None,0,"{""calendar_date"":""2023-02-16"",""calories_active...",None,14393,19,<NA>,19,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...
9,2023-05-09 09:50:28.224421+00:00,2023-05-09 09:50:28.224450+00:00,359,2023-03-11 00:00:00+00:00,93c4f1d5-5289-4c82-8680-239897012770,2919.0,501.0,12483,10621.0,250.0,...,18,None,0,"{""calendar_date"":""2023-03-11"",""calories_active...",None,14584,19,<NA>,19,{'uuid': '7426eadf-8398-4d41-86a4-0e3400000000...

Warning: Total number of columns (22) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df2 = df[['low','medium','high']]
df2.head(5)

      low  medium  high
0  4189.0  8591.0   3.0
1     NaN     NaN   NaN
2     NaN     NaN   NaN
3     NaN     NaN   NaN
4     NaN     NaN   NaN

In [ ]:
import pandas as pd
import sqlalchemy

In [ ]:
df = client.query("SELECT * FROM `woe-system.postgres_rds_public_datstream.public_biometrics_vital_summary_activity` LIMIT 1000").to_dataframe()

NameError: name 'engine' is not defined